In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn import svm
from sklearn import datasets

In [2]:
iris=datasets.load_iris()

In [6]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
df['flowers']=iris.target
df['flowers']=df['flowers'].apply(lambda x:iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

       flowers  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(iris.data,iris.target,test_size=0.3)

In [14]:
len(X_train)

105

In [15]:
len(X_test)

45

In [16]:
model=svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.9777777777777777

In [17]:
from sklearn.model_selection import cross_val_score

In [22]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [23]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [24]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [26]:
kernels={'rbf','linear'}
c=[1,10,20]
avg_scores={}
for kval in kernels:
    for cval in c:
        cv_scores=cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_scores[kval+'_'+str(cval)]=np.average(cv_scores)
avg_scores

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}

In [27]:
#instead of writing whole code above we can perform same operation by using gridsearchCV
from sklearn.model_selection import GridSearchCV

In [30]:
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['linear','rbf']
},cv=5, return_train_score=False)

In [32]:
clf.fit(X_train,Y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['linear', 'rbf']})

In [33]:
clf.cv_results_

{'mean_fit_time': array([0.00060225, 0.00075049, 0.00050263, 0.00098209, 0.0008018 ,
        0.00100813]),
 'std_fit_time': array([0.00049174, 0.00040996, 0.0004471 , 0.00038041, 0.00040091,
        0.00064294]),
 'mean_score_time': array([0.00073462, 0.00040073, 0.00070319, 0.00030055, 0.00040097,
        0.00020003]),
 'std_score_time': array([0.00042737, 0.0004908 , 0.00060233, 0.0004002 , 0.00049109,
        0.00040007]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'}],


In [39]:
df=pd.DataFrame(clf.cv_results_)
df.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.000602      0.000492         0.000735        0.000427       1   
1       0.000750      0.000410         0.000401        0.000491       1   
2       0.000503      0.000447         0.000703        0.000602      10   
3       0.000982      0.000380         0.000301        0.000400      10   
4       0.000802      0.000401         0.000401        0.000491      20   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}           1.000000   
1          rbf      {'C': 1, 'kernel': 'rbf'}           0.904762   
2       linear  {'C': 10, 'kernel': 'linear'}           0.952381   
3          rbf     {'C': 10, 'kernel': 'rbf'}           0.952381   
4       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000                1.0           1.000000           0.952381   
1           1.000000                1.0           0.952381           0.952381   
2           0.952381                1.0           0.952381           0.952381   
3           0.904762                1.0           0.952381           0.952381   
4           1.000000                1.0           0.952381           0.952381   

   mean_test_score  std_test_score  rank_test_score  
0         0.990476        0.019048                1  
1         0.961905        0.035635                3  
2         0.961905        0.019048                3  
3         0.952381        0.030117                5  
4         0.980952        0.023328                2

In [53]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.990476
1       1          rbf         0.961905
2      10       linear         0.961905
3      10          rbf         0.952381
4      20       linear         0.980952
5      20          rbf         0.942857

In [54]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_fe

In [55]:
clf.best_score_

0.9904761904761905

In [56]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [57]:
#now we will be using random vectorizer which will select and iterates only 2 from the datasets
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False,n_iter=2)

In [58]:
rs.fit(X_train,Y_train)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [59]:
rs.cv_results_

{'mean_fit_time': array([0.0006012 , 0.00079851]),
 'std_fit_time': array([0.00049088, 0.00039926]),
 'mean_score_time': array([0.00060024, 0.00020061]),
 'std_score_time': array([0.0004901 , 0.00040121]),
 'param_kernel': masked_array(data=['rbf', 'linear'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[20, 1],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 20}, {'kernel': 'linear', 'C': 1}],
 'split0_test_score': array([0.9047619, 1.       ]),
 'split1_test_score': array([0.9047619, 1.       ]),
 'split2_test_score': array([1., 1.]),
 'split3_test_score': array([0.95238095, 1.        ]),
 'split4_test_score': array([0.95238095, 0.95238095]),
 'mean_test_score': array([0.94285714, 0.99047619]),
 'std_test_score': array([0.03563483, 0.01904762]),
 'rank_test_score': array([2, 1])}

In [61]:
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      20          rbf         0.942857
1       1       linear         0.990476

In [63]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [64]:
model_params={
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbd','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    }
}


In [72]:
scores=[]
for model_name,mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })

C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py", line 180, in fit
    self._validate_params()
  File "C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", li

In [73]:
df=pd.DataFrame(scores,columns=['model','best_score','best_params'])
df.head()

model  best_score                   best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'linear'}
1        random_forest    0.946667           {'n_estimators': 5}
2  logistic_regression    0.966667                      {'C': 5}

In [74]:
import pickle

In [75]:
with open('Hyper_parameter_tuning','wb') as f:
    pickle.dump(model,f)