In [66]:
!pip install cross_val_score

ERROR: Could not find a version that satisfies the requirement cross_val_score (from versions: none)
ERROR: No matching distribution found for cross_val_score

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier

In [6]:
digits=load_digits()

In [7]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [8]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [9]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,Y_train,Y_test=train_test_split(digits.data,digits.target,test_size=0.2)

In [12]:
len(X_train)

1437

In [13]:
len(X_test)

360

In [14]:
model=LogisticRegression()
model

LogisticRegression()

In [15]:
model.fit(X_train,Y_train)

C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
model.score(X_test,Y_test)

0.9666666666666667

In [17]:
model_svm=SVC()

In [18]:
model_svm.fit(X_train,Y_train)

SVC()

In [19]:
model_svm.score(X_test,Y_test)

0.9916666666666667

In [20]:
model_rf=RandomForestClassifier(n_estimators=40)


In [21]:
model_rf.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=40)

In [22]:
model_rf.score(X_test,Y_test)

0.975

In [23]:
from sklearn.model_selection import KFold

In [24]:
model_kf=KFold(n_splits=3)

In [27]:
for train_index,test_index in model_kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [28]:
def get_score(model_score,X_train,X_test,Y_train,Y_test):
    model_score.fit(X_train,Y_train)
    return model_score.score

In [32]:
from sklearn.model_selection import StratifiedKFold
fold=StratifiedKFold(n_splits=3)

In [56]:
scores_l=[]
scores_svm=[]
scores_rf=[]

In [57]:
from sklearn.preprocessing import StandardScaler
for train_index,test_index in model_kf.split(digits.data):
    X_train,X_test,Y_train,Y_test=digits.data[train_index],digits.data[test_index],\
    digits.target[train_index],digits.target[test_index]

In [58]:
scores_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, Y_train, Y_test))  

In [59]:
scores_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))

In [63]:
scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))

In [64]:
print(scores_svm)

[<bound method ClassifierMixin.score of SVC()>]


In [67]:
from sklearn.model_selection import cross_val_score

In [68]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [69]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [71]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.92222222, 0.90277778, 0.96100279, 0.96100279, 0.91086351])