In [29]:
!pip install MultiNomialNB

ERROR: Could not find a version that satisfies the requirement MultiNomialNB (from versions: none)
ERROR: No matching distribution found for MultiNomialNB

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt



In [8]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

performing EDA on category 

In [9]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [10]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [12]:
X=df.Message
Y=df.spam

In [55]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25)

In [56]:
from sklearn.feature_extraction.text import CountVectorizer

In [57]:
v=CountVectorizer()
X_train_count=v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [58]:
from sklearn.naive_bayes import MultinomialNB

In [59]:
model=MultinomialNB()

In [60]:
model.fit(X_train_count,Y_train)

MultinomialNB()

In [61]:
emails=[
    'Nah I dont think he goes to usf, he lives around here though',
    'Upto 20% discount on parking, exclusive offer just for you.dont miss the reward'
]
emails_count=v.transform(emails)


In [62]:
model.predict(emails_count)

array([0, 1], dtype=int64)

In [63]:
X_test_count=v.transform(X_test)

In [64]:
model.score(X_test_count,Y_test)

0.9820531227566404

In [65]:
from sklearn.pipeline import Pipeline

In [68]:
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [69]:
clf.fit(X_train,Y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [70]:
clf.score(X_test,Y_test)

0.9820531227566404

In [71]:
clf.predict(emails)

array([0, 1], dtype=int64)

In [73]:
import pickle


In [74]:
with open('Email_spam_detection','wb') as f:
    pickle.dump(model,f)

In [75]:
with open('Email_spam_detection','rb') as f:
    pickle.load(f)