In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [11]:
df=pd.read_csv("diabetes1.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [12]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [13]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [14]:
df.Outcome.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [16]:
X=df.drop("Outcome",axis="columns")
Y=df.Outcome

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler=MinMaxScaler()
X_scaled=scaler.fit_transform(X)
X_scaled

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,Y_train,Y_test=train_test_split(X_scaled,Y,test_size=0.7)

In [21]:
X_train

array([[0.05882353, 0.51256281, 0.60655738, ..., 0.58867362, 0.09180188,
        0.35      ],
       [0.17647059, 0.48241206, 0.63934426, ..., 0.55588674, 0.06831768,
        0.31666667],
       [0.11764706, 0.70854271, 0.47540984, ..., 0.37853949, 0.26515798,
        0.05      ],
       ...,
       [0.11764706, 0.34170854, 0.50819672, ..., 0.29955291, 0.0764304 ,
        0.03333333],
       [0.52941176, 0.45728643, 0.55737705, ..., 0.36065574, 0.05209223,
        0.61666667],
       [0.17647059, 0.44723618, 0.60655738, ..., 0.45305514, 0.20196413,
        0.28333333]])

In [22]:
X_test

array([[0.05882353, 0.59296482, 0.47540984, ..., 0.49627422, 0.07813834,
        0.03333333],
       [0.17647059, 0.64321608, 0.63934426, ..., 0.31445604, 0.08112724,
        0.56666667],
       [0.11764706, 0.69849246, 0.6147541 , ..., 0.38152012, 0.03800171,
        0.13333333],
       ...,
       [0.17647059, 0.55778894, 0.47540984, ..., 0.43964232, 0.15029889,
        0.01666667],
       [0.23529412, 0.49748744, 0.55737705, ..., 0.48882265, 0.02860803,
        0.2       ],
       [0.        , 0.5678392 , 0.6557377 , ..., 0.46199702, 0.33988044,
        0.        ]])

In [23]:
Y_train.value_counts()

0    146
1     84
Name: Outcome, dtype: int64

In [24]:
Y_test.value_counts()

0    354
1    184
Name: Outcome, dtype: int64

Train using stand alone model

In [27]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [29]:
model1=DecisionTreeClassifier()
scores=cross_val_score(model1,X,Y,cv=5)
scores

array([0.67532468, 0.66233766, 0.67532468, 0.81045752, 0.74509804])

In [30]:
scores.mean()

0.7137085137085137

Now train the model using bagging classifier

In [31]:
from sklearn.ensemble import BaggingClassifier

In [35]:
bag_model=BaggingClassifier(
    base_estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)

In [36]:
bag_model.fit(X_train,Y_train)

C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=DecisionTreeClassifier(), max_samples=0.8,
                  n_estimators=100, oob_score=True, random_state=0)

In [39]:
bag_model.oob_score_

0.782608695652174

In [40]:
bag_model.score(X_test,Y_test)

0.7434944237918215

In [41]:
bag_model=BaggingClassifier(
    base_estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)

In [43]:
scores=cross_val_score(bag_model,X,Y,cv=5)

C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:166: Futu

In [44]:
scores.mean()

0.7578728461081402

We can see some improvement in the score

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
model2=RandomForestClassifier(n_estimators=50)

In [48]:
scores=cross_val_score(model2,X,Y,cv=5)
scores.mean()

0.7591885238944063

In [49]:
import pickle

In [50]:
with open("Bagging_model","wb") as f:
    pickle.dump(model2,f)

In [52]:
with open("Bagging_model","rb") as f:
    pickle.load(f)