In [18]:
!pip install sklearn.externals

ERROR: Could not find a version that satisfies the requirement sklearn.externals (from versions: none)
ERROR: No matching distribution found for sklearn.externals


In [6]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [7]:
df = pd.read_csv("Linear Regression Dataset.csv.xls")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [8]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [9]:
model.coef_

array([135.78767123])

In [10]:
model.intercept_

180616.43835616432

In [11]:
model.predict([[5000]])

C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [12]:
import pickle

In [13]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [14]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)

In [15]:
mp.predict([[5000]])

C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [21]:
 import joblib

In [22]:
joblib.dump(model,"model_joblib")

['model_joblib']

In [27]:
mj=joblib.load("model_joblib")
mj

LinearRegression()

In [32]:
mj.coef_

array([135.78767123])

In [31]:
mj.intercept_

180616.43835616432

In [28]:
mj.predict([[5000]])

C:\Users\saite\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])